### ISSUE TITLE
Is this a WIP? Error when trying to mine

### ISSUE THREAD

**Issue by MiningCryptoLive** [muscleman/progpowz-nodejs-pool#1]
Hello,

thanks for this repo. I have tried to build a zano pool using the instructions. Everything builds and the pool starts. When I try to connect a miner to it I get the following error. 
Exception: utils.cnUtil.get_hash_from_block_template_with_extra is not a function
Message id 5 method eth_getWork

**Comment by muscleman** [comment]
strange, because if the zano-node-util library is installed from the package.json file get_hash_from_block_template_with_extra is clearly available.
https://github.com/hyle-team/zano-node-util/blob/master/src/main.cc#L184b

**Comment by muscleman** [comment]
maybe the issue is that i pointed the package.json package for cryptoforknote-util to the hyle-team repo's version and they didn't approve the pr until after you attempted to pull the library. so you got an old version.

my pr into the zano-node-utils has been approved now, try again.

I also tested this several times to make sure everything worked, since i had the code in a private repo not compatiable with github forks.

also tested 3 times tonight,
worked fine with node 12, 14 and wouldn't compile with 16
miner hashed on the pool and pool accepted shares.

see here.
https://testv2.smartcoinpool.net/

**Comment by MiningCryptoLive** [comment]
> closing this issue, i see your mining [zano.miningcrypto.live](https://zano.miningcrypto.live/)

yes, I got it working. Had to delete the repo and cloned it again. Working great. Thanks
